name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SetUp Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Clone a Script Repo
        run: |
          git clone https://github.com/vitiwariptc/cicdDemo.git cicdDemo
          cd cicdDemo
          ls -la

      - name: Install Dependencies
        run: |
          cd cloned-repo
          python -m pip install --upgrade pip
          pip install -r cicdDemo/requirements.txt
            
      - name: Run Python File
        run: |
            cd cicdDemo
            python mathOperations.py
      