name: CI2 Workflow

on:
  workflow_run:
    workflows:
      - CI Workflow
      - Workflow B
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: SetUp Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Clone a Script Repo
        run: |
          git clone https://github.com/vitiwariptc/cicdDemo.git cicdDemo
          cd cicdDemo
          ls -la

      - name: Install Dependencies
        run: |
          cd cicdDemo
          python -m pip install --upgrade pip
          pip install -r requirements.txt
            
      - name: Run Python File
        run: |
            cd cicdDemo/src
            python mathOperations.py
      