name: Auto-Merge PR with GH CLI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
      # Authenticate GitHub CLI using GITHUB_TOKEN
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.MY_GITHUB_TOKEN }}" | gh auth login --with-token

      # Enable auto-merge on the pull request
      - name: Enable Auto-Merge
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --repo ${{github.repository}} --auto --merge
